# Generated by Django 3.2.13 on 2022-06-28 09:29

import core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('type', models.CharField(choices=[('Candidate', 'Candidate'), ('Recruiter', 'Recruiter')], default='Candidate', max_length=15)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('link', models.URLField()),
                ('slug', models.SlugField(allow_unicode=True, unique=True)),
                ('company_goal', models.TextField()),
                ('employee_count', models.IntegerField()),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CompanyFounder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('year_founded', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(allow_unicode=True, unique=True)),
                ('title', models.CharField(default='Data Science', max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('requirement', models.TextField()),
                ('job_description', models.TextField()),
                ('skillset', models.TextField()),
                ('vacancies', models.IntegerField()),
                ('ctc', models.IntegerField()),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='job_company', to='core.company')),
            ],
        ),
        migrations.CreateModel(
            name='Recruiter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(allow_unicode=True, unique=True)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('phone_number', models.IntegerField()),
                ('city', models.CharField(max_length=255)),
                ('avatar', models.ImageField(upload_to=core.models.avatar_image_file_path)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recruiter_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Recruitment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recruiter_company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recruiter_company', to='core.company')),
                ('recruiter_for_job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recruiter_for_job', to='core.job')),
                ('recruiter_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recruiter_profile', to='core.recruiter')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(allow_unicode=True, unique=True)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('phone_number', models.IntegerField()),
                ('city', models.CharField(max_length=255)),
                ('avatar', models.ImageField(upload_to=core.models.avatar_image_file_path)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='job',
            name='recruiter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_recruiter', to='core.recruiter'),
        ),
        migrations.AddField(
            model_name='company',
            name='founders',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='founders', to='core.companyfounder'),
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.TextField()),
                ('job_application_candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_application_candidate', to=settings.AUTH_USER_MODEL)),
                ('job_application_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_application_job', to='core.job')),
            ],
            options={
                'unique_together': {('job_application_candidate', 'job_application_job')},
            },
        ),
    ]
