# Generated by Django 3.2.13 on 2022-06-24 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20220624_2335'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recruiter',
            name='company_user',
        ),
        migrations.RemoveField(
            model_name='recruiter',
            name='email',
        ),
        migrations.AddField(
            model_name='recruiter',
            name='user_recruiter',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_recruiter', to='core.user'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=255)),
                ('requirement', models.TextField()),
                ('job_description', models.TextField()),
                ('skillset', models.TextField()),
                ('vacancies', models.IntegerField()),
                ('ctc', models.IntegerField()),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='job_company', to='core.company')),
                ('recruiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_recruiter', to='core.recruiter')),
            ],
        ),
    ]
