# Generated by Django 3.2.13 on 2022-06-24 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20220624_2350'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recruiter',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='recruiter',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='recruiter',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='recruiter',
            name='user_recruiter',
        ),
        migrations.AddField(
            model_name='recruiter',
            name='recruiter_profile',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='recruiter_profile', to='core.profile'),
            preserve_default=False,
        ),
    ]
