# Generated by Django 3.2.13 on 2022-06-24 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20220625_0012'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recruiter',
            old_name='company',
            new_name='recruiter_company',
        ),
    ]
