# Generated by Django 3.2.13 on 2022-06-24 19:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_company_recruiter_recruiter_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.TextField()),
                ('job_application_candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_application_candidate', to=settings.AUTH_USER_MODEL)),
                ('job_application_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_application_company', to='core.company')),
            ],
        ),
    ]
