# Generated by Django 3.2.13 on 2022-06-24 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_jobapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='title',
            field=models.CharField(default='Data Science', max_length=255),
        ),
    ]
